// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN-gex2A99ZpW-CHxFApN2SPrq1nCn3Tg',
    appId: '1:870648020610:web:9dbd901efc1f63d35d7e9b',
    messagingSenderId: '870648020610',
    projectId: 'lkw1fbase1-8fc4b',
    authDomain: 'lkw1fbase1-8fc4b.firebaseapp.com',
    storageBucket: 'lkw1fbase1-8fc4b.appspot.com',
    measurementId: 'G-1SP94CH745',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzUKQrDqZ-xSlxL-aMN0ox9ft-T_7ngE',
    appId: '1:870648020610:android:7279fd0ee544b0275d7e9b',
    messagingSenderId: '870648020610',
    projectId: 'lkw1fbase1-8fc4b',
    storageBucket: 'lkw1fbase1-8fc4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcPVkLD-UXJ8CTNBj8n7flry1wG4V4DG4',
    appId: '1:870648020610:ios:bc8dbec83fbb6bd95d7e9b',
    messagingSenderId: '870648020610',
    projectId: 'lkw1fbase1-8fc4b',
    storageBucket: 'lkw1fbase1-8fc4b.appspot.com',
    iosBundleId: 'com.example.lkw1fbase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcPVkLD-UXJ8CTNBj8n7flry1wG4V4DG4',
    appId: '1:870648020610:ios:cf498cee402db3905d7e9b',
    messagingSenderId: '870648020610',
    projectId: 'lkw1fbase1-8fc4b',
    storageBucket: 'lkw1fbase1-8fc4b.appspot.com',
    iosBundleId: 'com.example.lkw1fbase1.RunnerTests',
  );
}
